AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
  Exclude:
    - 'Rakefile'
    - '*.gemspec'

AndOr:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Naming/FileName:
  Enabled: false
